### ISSUE TITLE
Crashes on empty bucket

### ISSUE THREAD

**Issue by Nebucatnetzer** [lusingander/stu#10]
I tested it against an empty bucket and it crashed with the following message:

```
thread 'main' panicked at src/pages/object_list.rs:151:17:
selected index 0 is out of range 0
```

**Comment by lusingander** [comment]
Thank you for your report. Seems to be a regression in v0.4.2 😢

**Comment by lusingander** [comment]
https://github.com/lusingander/stu/commit/52c87450e18137e4cd9f704002098893b8d85128

It will be released in the next version.
