### ISSUE TITLE
Filter bucket list by region

### ISSUE THREAD

**Issue by henrikskog** [lusingander/stu#12]
I have found this tool super useful, thank you for making it! Due to the problem described I first thought that the program did not work at all, as I could not open any of my buckets. This is why I think it's worth fixing. 

The list of buckets show all buckets in the aws account for all regions. This makes it seem like they can all be accessed. However when trying to open a bucket that resides in a different region than specified (`ap-northeast-1` by default), it fails with the error `ERROR: Failed to load objects`.  It would be really useful to show a `invalid bucket region` or something in this case to avoid confusion. 

If you want I can make a pull request on this :) I have zero experience with rust so it would be interesting to give it a shot.

**Comment by lusingander** [comment]
Thank you for reporting this, and thank you for your interest in this project.

I was not aware of the problem. Let me check a few things just to be sure.

- Is the connection to the actual AWS (not localstack, etc.)?
- When an error occurs, what is output to `$STU_ROOT_DIR/error.log`?

It's nice to have an error message, but we probably don't need to show buckets other than the regions specified, as it's not useful with this tool.

**Comment by henrikskog** [comment]
It's a connection to aws, yes. 

Filtering the list of buckets to only show buckets in the specified region makes sense. In this case, the error you get from trying to open a bucket in a different region is not relevant to this issue.
