### ISSUE TITLE
Support Garage

### ISSUE THREAD

**Issue by williamdes** [lusingander/stu#18]
Garage is a pure Rust S3 server: https://garagehq.deuxfleurs.fr/

They do not support versions yet: https://git.deuxfleurs.fr/Deuxfleurs/garage/issues/166

https://garagehq.deuxfleurs.fr/documentation/reference-manual/s3-compatibility/

Endpoint | Garage | Openstack Swift | Ceph Object Gateway | Riak CS | OpenIO
-- | -- | -- | -- | -- | --
DeleteBucketLifecycle | ✅ Implemented | ❌ | ✅ | ❌ | ✅
GetBucketLifecycleConfiguration | ✅ Implemented | ❌ | ✅ | ❌ | ✅
PutBucketLifecycleConfiguration | ⚠ Partially implemented (see below) | ❌ | ✅ | ❌ | ✅
GetBucketVersioning | ❌ Stub (see below) | ✅ | ✅ | ❌ | ✅
ListObjectVersions | ❌ Missing | ❌ | ✅ | ❌ | ✅
PutBucketVersioning | ❌ Missing | ❌ | ✅ | ❌ | ✅

**Comment by williamdes** [comment]
For me this would qualify as a bug `ERROR: Failed to load object versions`
When I try to view an object

**Comment by lusingander** [comment]
When retrieving object details, version information is also retrieved, which causes an error.

It might be a good idea to handle the missing information in the tab, or to retrieve it when the tab is opened. Even if you are using S3, the same problem can occur due to permissions.

**Comment by lusingander** [comment]
I haven't confirmed whether it works with "Garage", but I've fixed as mentioned in the comment above.

**Comment by williamdes** [comment]
> I haven't confirmed whether it works with "Garage", but I've fixed as mentioned in the comment above.

Thank you, this fix works fine with Garage 🎉

**Comment by lusingander** [comment]
> Thank you, this fix works fine with Garage 🎉

Great!
