### ISSUE TITLE
Option to refresh current view

### ISSUE THREAD

**Issue by augustwester** [lusingander/stu#19]
This is a really cool project that I could see myself using every day! However, I really miss an option to refresh the current view. 

Would this be possible to add?

**Comment by lusingander** [comment]
Thank you for your interest in this project.

Does "refresh" mean to reload buckets and objects?
If so, I think it would be better to have that feature.

Currently, the bucket and object lists are cached for each path while the application is running, so if there are updates, we need to run the application again.

**Comment by augustwester** [comment]
Yes, I noticed that. I currently have no insight into the internals of the app, so I'm not sure what the best way to implement this is. All I know is that it would be nice to press `r` and have the contents of the location I'm looking at update.

FWIW, I work in machine learning and often find myself populating S3 with new data. When I trigger a long-running data generation script, it would be nice to see the contents of S3 update. Would love to do it through stu 🙂

**Comment by lusingander** [comment]
Thanks!

> it would be nice to press r and have the contents of the location I'm looking at update

Yeah, I am thinking of doing something like that too.
