### ISSUE TITLE
Region is not loaded from AWS config

### ISSUE THREAD

**Issue by williamdes** [lusingander/stu#23]
`.aws/config`

```ini
[profile mail-server-wdes-intranet]
region = garage
services = garage
endpoint_url = http://x.x.x.x:3900

[services garage]
s3 =
  endpoint_url = http://x.x.x.x:3900
```

Running: `stu --profile mail-server-wdes-intranet` it does not use the region but `ap-northeast-1`. Checked in debug log.

Maybe it is only the `unexpected scope:` ?

```xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AuthorizationHeaderMalformed</Code><Message>Authorization header malformed, unexpected scope: 20240908/ap-northeast-1/s3/aws4_request</Message><Resource>/</Resource><Region>garage</Region></Error>
```

That said passing --region garage makes it work

**Comment by lusingander** [comment]
Thanks for reporting, it certainly does seem to not be loading 😕

**Comment by lusingander** [comment]
[I would expect it to be loaded by the Default Region Provider](https://github.com/lusingander/stu/blob/afbf4b62ec99c822c2d27465226ea8028d0f1dc1/src/client.rs#L36
), but it doesn't seem to be loaded. At least it seems to be loaded when specified by the environment variable `AWS_REGION`.

**Comment by williamdes** [comment]
Thank you for looking into it
`ap-northeast-1/s3/aws4_request</Message><Resource>/</Resource><Region>garage`
Shows some part of the code knows the region and another part does not, this is quite an interesting bug

**Comment by williamdes** [comment]
The new version of stu (`0.6.0`) now does a better error message: `No bucket found (region: us-east-1)` with `stu --profile mail-server-wdes-intranet`

**Comment by lusingander** [comment]
The implementation up to `0.5.2` was as follows:

1. If `--region` is set, use it.
1. If AWS default value (environment variable, profile, etc.) is set, use it.
1. If none of them can be obtained, use the default value (`ap-northeast-1`).

In `0.6.0`, users can now set the default value of `3` individually as a configuration.

On the other hand, this issue is about the profile value not being loaded correctly in `2`.

**Comment by evanofslack** [comment]
I am also seeing the issue, I would have expected the region from my aws profile to be used, but I have to specify it manually. Following.

**Comment by lusingander** [comment]
https://github.com/lusingander/stu/releases/tag/v0.6.2

**Comment by williamdes** [comment]
Thank you !
It works fine 🎉

**Comment by lusingander** [comment]
Thanks for checking!
