### ISSUE TITLE
Brew installation on Linux

### ISSUE THREAD

**Issue by farzadmf** [lusingander/stu#26]
Hi, Homebrow is also an option to install packages on Linux (I personally use it for a lot of my packages).

It seems like `stu` only supports MacOS for brew installation; is it possible to add Linux support as well?

**Comment by lusingander** [comment]
Added with https://github.com/lusingander/homebrew-tap/commit/cd946cea7543155921ba0e54d297ba876762f988

If we want to add other targets, we will need to consider the build settings separately.

**Comment by farzadmf** [comment]
Thank you @lusingander for this; I appreciate it.

I was wondering if it would be possible to install a statically built binary with `brew`? I'm installing `stu` on a Linux distribution with old GCC libs, and I'm getting this when I run it:
```
stu: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by stu)
stu: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by stu)
stu: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by stu)
stu: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by stu)
stu: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by stu)
stu: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by stu)
stu: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by stu)
```

**Comment by lusingander** [comment]
Thanks for confirming.

And sorry, currently we only build dynamically linked binaries, we need to build and release statically linked binaries, and it would be nice to change the binaries we distribute with brew.
