### ISSUE TITLE
Config-free Operation

### ISSUE THREAD

**Issue by ztroop** [lusingander/stu#6]
Great utility! It would be ideal to not have to provide a configuration file or parameters but instead derive AWS configuration through the environment variables:

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Comment by ztroop** [comment]
Well, bucket name would still need to be specified. 😅

**Comment by lusingander** [comment]
What kind of usage do you envision? I think values such as `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_PROFILE`, `AWS_CONFIG_FILE` are read and set.

**Comment by ztroop** [comment]
I was thinking that the endpoint url could be inferred as default if the AWS_REGION is set. Ideally then, the only thing needed to specify is the bucket to examine.

**Comment by lusingander** [comment]
Does that mean it's not working correctly if you specify only region and not endpoint-url? I think it will work without specifying endpoint-url unless you are connecting to localstack or minio.

**Comment by ztroop** [comment]
It wasn't while I was testing it. I skimmed over the code and didn't see any environment variable usage around this, so I had assumed this was the cause.

However, I'll try again as my session may have had these unset at the time. I'll update this issue again after I have a chance to validate this.

**Comment by lusingander** [comment]
If an error occurs, `$STU_ROOT_DIR/error.log` may help. (This is a log to assist development, so it may not necessarily be easy to read and contain useful information.)

**Comment by ztroop** [comment]
Confirmed, it looks like it loads just fine without parameters. Closing.
