### ISSUE TITLE
Slow / Stopped Interface In Listing View

### ISSUE THREAD

**Issue by ztroop** [lusingander/stu#7]
I noticed that while accessing a bucket, I experienced a significant slow-down or freeze, where the interface no longer responded to key events. No errors in `$STU_ROOT_DIR/error.log`, this is where I get stuck:

<img width="711" alt="Screenshot 2024-04-05 at 10 51 44 PM" src="https://github.com/lusingander/stu/assets/5018339/358df5a2-bb7d-405b-ae36-6de46cc480fb">

Each folder has dozens of *.mkv video files ranging from 20-200MB.

**Comment by lusingander** [comment]
- Does it only happen in certain buckets or paths? Is it reproducible?
- Does it stop right after opening the list? Or when trying to perform some other operation (such as opening object details)?

**Comment by ztroop** [comment]
- Not sure, I'll have to experiment.
- Right after opening the list - no other operation.

**Comment by ztroop** [comment]
I had another bucket, with ~15 folders with 5-20 *.mkv video files. (similar to the other bucket in that respect). Same result.

**Comment by lusingander** [comment]
I have never encountered this problem, so I need more information or an environment to reproduce it to resolve the issue.

**Comment by lusingander** [comment]
Please reopen it if necessary and provide the details as given in the link below.
https://github.com/lusingander/stu?tab=readme-ov-file#troubleshooting
